version: "3.2"
services:
  web:
    image: server
    ports:
      - "40000:18000"
    networks:
      - net1
    depends_on:
      - redis
    volumes:
      - type: volume
        source: webcode
        target: /home/myapp
      - "/etc/localtime:/etc/localtime:ro"
  redis:
    image: redis
    ports:
      - "63790:6379"
    networks:
      - net1
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
networks:
  net1:
volumes:
  webcode: