version: "3.2"
services:
  redis:
    image: redis:1.0
    ports:
      - "63790:6379"
    networks:
      - default
      - myapp_net
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
networks:
  myapp_net:
    external: true
volumes:
  webcode: