version: "3.2"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - default
      - myapp_net
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/mongodb/data:/data/db"
networks:
  myapp_net:
    external: true