version: "3.2"
services:
  web:
    image: server
    ports:
      - "30000:3000"
    volumes:
      - type: volume
        source: webcode
        target: /home/myapp
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - default
      - myapp_net
    # external_links:
    #   - myapp_redis_1
volumes:
  webcode:
networks:
  myapp_net:
    external: true