version: "3.2"
services:
  authorizer:
    image: wxtoken
    networks:
      - default
      - myapp_net
    volumes:
      - "code:/home/node/myapp"
      - "/etc/localtime:/etc/localtime:ro"
    command: ["node", "bin/authorizer_access_token.js"]
networks:
  myapp_net:
    external: true
volumes:
  code: