version: "3.2"
services:
  web:
    image: radar
    ports:
      - "40004:3000"
    networks:
      - default
      - myapp_net
    volumes:
      - "code:/home/node/radar"
      - "/etc/localtime:/etc/localtime:ro"
networks:
  myapp_net:
    external: true
volumes:
  code: