version: "3.2"
services:
  web:
    image: node
    networks:
      - default
      - myapp_net
    volumes:
      - "code:/home/node/myapp"
      - "/etc/localtime:/etc/localtime:ro"
networks:
  myapp_net:
    external: true
volumes:
  code: